// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.3.0; do not edit! //
// ---------------------------------------------------------------- //

// Derived from the Raspberry Pi substep counter/age protocol.
// Copyright (c) 2023 Raspberry Pi (Trading) Ltd.
// Copyright (c) 2026 Ryota SUZUKI
// SPDX-License-Identifier: BSD-3-Clause
#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

#ifdef __cpp_constexpr
#define __pio_const constexpr
#else
#define __pio_const const
#endif

// ------------ //
// pair_encoder //
// ------------ //

#define pair_encoder_wrap_target 0
#define pair_encoder_wrap 31
#define pair_encoder_pio_version 0

static __pio_const uint16_t pair_encoder_program_instructions[] = {
            //     .wrap_target
    0x4020, //  0: in     x, 32
    0x4040, //  1: in     y, 32
    0xa0e2, //  2: mov    osr, y
    0x60c1, //  3: out    isr, 1
    0x4001, //  4: in     pins, 1
    0xa0ae, //  5: mov    pc, ~isr
    0x0187, //  6: jmp    y--, 7                 [1]
    0xe021, //  7: set    x, 1
    0xa031, //  8: mov    x, ::x
    0x0010, //  9: jmp    16
    0xa04a, // 10: mov    y, ~y
    0x008c, // 11: jmp    y--, 12
    0xa04a, // 12: mov    y, ~y
    0xe020, // 13: set    x, 0
    0x0010, // 14: jmp    16
    0x0102, // 15: jmp    2                      [1]
    0x0051, // 16: jmp    x--, 17
    0xa0ed, // 17: mov    osr, ~status
    0x60a4, // 18: out    pc, 4
    0x00d5, // 19: jmp    pin, 21
    0x0006, // 20: jmp    6
    0x000a, // 21: jmp    10
    0x00d8, // 22: jmp    pin, 24
    0x000a, // 23: jmp    10
    0x0006, // 24: jmp    6
    0x0002, // 25: jmp    2
    0x0002, // 26: jmp    2
    0x0002, // 27: jmp    2
    0x0710, // 28: jmp    16                     [7]
    0x0016, // 29: jmp    22
    0x0013, // 30: jmp    19
    0x0710, // 31: jmp    16                     [7]
            //     .wrap
};

#if !PICO_NO_HARDWARE
static __pio_const struct pio_program pair_encoder_program = {
    .instructions = pair_encoder_program_instructions,
    .length = 32,
    .origin = 0,
    .pio_version = pair_encoder_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config pair_encoder_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + pair_encoder_wrap_target, offset + pair_encoder_wrap);
    return c;
}
#endif

